Resources:
  detectron2S3Role:
        Type: AWS::IAM::Role
        Properties:
          RoleName: detectron2S3Role
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - ec2.amazonaws.com
                Action:
                  - sts:AssumeRole
          Path: /
  S3AcessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3AcessPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:ListBucket"
            Resource: 
              - !Join [ "", [ "arn:aws:s3:::", "${self:custom.detectron2_bucket}", "/*" ] ]
              - !Join [ "", [ "arn:aws:s3:::", "${self:custom.detectron2_bucket}"] ]
      Roles:
        - !Ref detectron2S3Role
  detectron2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: detectron2Profile
      Path: /
      Roles: 
        - !Ref detectron2S3Role